### PR TITLE
Fixed Composite Device Error on Windows OS

### PR DESCRIPTION
**Pull request by Spider84**
image

### CODE REVIEW

**Comment by amitesh-singh** [comment]
Very cool. Thanks.

I'll verify this on Linux and  test it once.

**Comment by Spider84** [comment]
```
[   82.530565] usb 3-2: new full-speed USB device number 5 using xhci_hcd
[   82.794019] usb 3-2: New USB device found, idVendor=16c0, idProduct=05dc, bcdDevice= 2.00
[   82.794020] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   82.794021] usb 3-2: Product: fastusbasp
[   82.794022] usb 3-2: Manufacturer: http://amitesh-singh.github.io
[   82.794022] usb 3-2: SerialNumber: 6D76245C5253
[   82.818933] cdc_acm 3-2:1.0: ttyACM0: USB ACM device
[   82.820046] usbcore: registered new interface driver cdc_acm
[   82.820047] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
```
```
pider@spider-ubuntu:~$ avrdude -p atmega328 -c usbasp-clone 

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: Expected signature for ATmega328 is 1E 95 14
         Double check chip, or use -F to override this check.

avrdude done.  Thank you.
```

```
C:\>C:\WinAVR-20100110\bin\avrdude -p atmega328 -c usbasp-clone

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e950f (probably m328p)
avrdude.exe: Expected signature for ATmega328 is 1E 95 14
             Double check chip, or use -F to override this check.

avrdude.exe done.  Thank you.
```

**Comment by Spider84** [comment]
image

**Comment by amitesh-singh** [comment]
Thanks, I'd merged the patches.
do you have a guide on how to setup FASTUSBasp on windows?

if possible, could you please provide a patch for README.md file? I'll be happy to accept your 
patch.

**Comment by Spider84** [comment]
1. Download [Zadig](https://zadig.akeo.ie/)
2. Insert device to USB. Wait while windows can't install them
3. Launch Zadig :)
4. Select in Zadig our device from ComboBox
5. Select driver Type **libusbK**
6. Press Install Driver
7. Wait while Zadig installing driver and Windows detecting device.
8. DONE.

Now you can use avrdude like software "as is". Device work.

CDC (Com Port) work by default. No need any actions from user.

**Comment by amitesh-singh** [comment]
Hi @Spider84 
I'd added few patches for fix some issue.
Whenever you get time, Could you please verify with latest code on Windows?
Thanks in advance.

**Pull request merged**
